name: crypto_id
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  ecdsa: ^0.1.0
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3
  elliptic: ^0.3.10
  sqflite: ^2.3.2
  path_provider: ^2.0.2
  path:
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/
    - lib/assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: lib/assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Urbanist-Bold.ttf
          weight: 700